### ISSUE TITLE
Práctica 

### ISSUE THREAD

**Issue by 23620126** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-23620126#2]
[practica matematicas discretas.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-23620126/files/12565845/practica.matematicas.discretas.pdf)

**Comment by Felix-Angel** [comment]
PORTADA 25%
PROCEDIMIENTO 25%
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS (FALTA DE LISTA DE ILUSTRACIONES) 15%
RESULTADOS Y CONCLUSIONES (NO COMPLETA LAS LINEAS DE TEXTO DE LA CONCLUSION, CUENTA CON 10) 22%
CALIFICACION: 87/100
CALIFICACION: 17.4/20
CALIFICADO POR: "EQUIPO DE MAYRA, DIEGO, DANIEL, FELIX"

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
